/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Tue Sep  4 15:02:36 2018. */

#include "sensorbug.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorBugMessage_fields[13] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, SensorBugMessage, counter, counter, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, SensorBugMessage, battery, counter, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, SensorBugMessage, light, battery, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, SensorBugMessage, pir_count, light, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, SensorBugMessage, motion_count, pir_count, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, SensorBugMessage, temperature, motion_count, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, SensorBugMessage, humidity, temperature, 0),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, SensorBugMessage, pressure, humidity, 0),
    PB_FIELD(  9, FLOAT   , SINGULAR, STATIC  , OTHER, SensorBugMessage, gas_resistance, pressure, 0),
    PB_FIELD( 10, UINT32  , SINGULAR, STATIC  , OTHER, SensorBugMessage, ambient_noise, gas_resistance, 0),
    PB_FIELD( 11, UINT32  , SINGULAR, STATIC  , OTHER, SensorBugMessage, report_periocd, ambient_noise, 0),
    PB_FIELD( 12, BOOL    , SINGULAR, STATIC  , OTHER, SensorBugMessage, motion_en, report_periocd, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
